name: 🐛 Bug Report / 버그 리포트
description: Report a bug found in StockQuest / StockQuest에서 발견한 버그를 신고해주세요
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Thank you for reporting a bug! / 버그 리포트를 작성해주셔서 감사합니다!
        
        Clear and detailed information will help us resolve the issue quickly.
        명확하고 상세한 정보를 제공해주시면 문제를 빠르게 해결할 수 있습니다.
        
  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 Bug Description / 버그 설명
      description: Describe the bug clearly and concisely. / 발생한 버그에 대해 명확하고 간결하게 설명해주세요.
      placeholder: "Example: Challenge list doesn't load after login / 예: 로그인 후 챌린지 목록이 로드되지 않습니다."
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 재현 단계
      description: 버그를 재현하기 위한 단계를 순서대로 작성해주세요.
      placeholder: |
        1. 메인 페이지로 이동
        2. '로그인' 버튼 클릭
        3. 올바른 계정 정보 입력
        4. 로그인 후 챌린지 페이지로 이동
        5. 오류 발생 확인
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 예상된 동작
      description: 정상적으로 작동했을 때 어떤 일이 일어나야 하는지 설명해주세요.
      placeholder: "챌린지 목록이 정상적으로 표시되어야 합니다."
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 실제 동작
      description: 실제로 어떤 일이 일어났는지 설명해주세요.
      placeholder: "빈 페이지가 표시되고 콘솔에 오류 메시지가 나타납니다."
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: 🧩 영향받는 컴포넌트
      description: 버그가 발생한 시스템 영역을 선택해주세요.
      options:
        - 사용자 인증 (로그인/회원가입)
        - 챌린지 시스템
        - 거래 시스템 (주문 접수/체결)
        - 포트폴리오 관리
        - 리더보드
        - 커뮤니티 (게시판)
        - 시장 데이터
        - UI/UX
        - 성능 이슈
        - 기타
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: 🚨 심각도
      description: 버그의 심각도를 선택해주세요.
      options:
        - 🔴 Critical (서비스 전체 중단)
        - 🟠 High (핵심 기능 사용 불가)
        - 🟡 Medium (일부 기능 제한)
        - 🟢 Low (사소한 불편)
        - 🔵 Enhancement (개선 제안)
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: 🌐 환경 정보
      description: 버그가 발생한 환경을 알려주세요.
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - 브라우저: Chrome 120.0, Firefox 121.0, Safari 17.0
        - Node.js 버전: 18.17.0
        - Java 버전: 21.0.1
      value: |
        - OS: 
        - 브라우저: 
        - 화면 해상도: 
        - 모바일 기기 (해당시): 
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: 📋 로그 및 에러 메시지
      description: 관련된 로그나 에러 메시지를 첨부해주세요.
      placeholder: |
        콘솔 에러:
        ```
        Error: Cannot read property 'data' of undefined
            at ChallengeList.tsx:45:12
        ```
        
        서버 로그:
        ```
        2024-09-11 10:30:15 ERROR [http-nio-8080-exec-1] c.s.a.GlobalExceptionHandler : Unexpected error
        java.lang.NullPointerException: ...
        ```
      render: shell
      
  - type: textarea
    id: screenshots
    attributes:
      label: 📸 스크린샷 또는 동영상
      description: 가능하다면 버그를 보여주는 스크린샷이나 동영상을 첨부해주세요.
      placeholder: "이미지를 드래그 앤 드롭하거나 붙여넣기 하세요."
      
  - type: textarea
    id: additional-context
    attributes:
      label: 📝 추가 정보
      description: 버그와 관련된 추가 정보나 컨텍스트가 있다면 제공해주세요.
      placeholder: |
        - 특정 데이터나 조건에서만 발생하는지
        - 이전에는 정상 작동했는지
        - 관련된 다른 이슈가 있는지
        - 임시 해결 방법이 있는지
        
  - type: checkboxes
    id: pre-submission-checklist
    attributes:
      label: ✅ 제출 전 체크리스트
      description: 이슈를 제출하기 전에 다음 사항을 확인해주세요.
      options:
        - label: 기존 이슈에 동일한 버그가 신고되지 않았는지 검색했습니다.
          required: true
        - label: 최신 버전에서 버그가 재현되는지 확인했습니다.
          required: true
        - label: 브라우저 캐시를 클리어하고 다시 시도해봤습니다.
          required: true
        - label: 개발자 도구의 콘솔에서 에러 메시지를 확인했습니다.
          required: true
        - label: 가능한 한 구체적이고 재현 가능한 정보를 제공했습니다.
          required: true