name: ⚡ 성능 이슈
description: StockQuest의 성능 문제를 신고해주세요
title: "⚡ [Performance]: "
labels: ["performance", "needs-investigation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚡ 성능 이슈 신고
        
        성능 문제는 사용자 경험에 직접적인 영향을 미칩니다. 
        구체적인 측정값과 재현 방법을 제공해주시면 빠른 해결에 도움이 됩니다.
        
  - type: textarea
    id: performance-issue
    attributes:
      label: 🐌 성능 문제 설명
      description: 경험한 성능 문제를 구체적으로 설명해주세요.
      placeholder: "예: 챌린지 목록 페이지 로딩이 5초 이상 걸리고, 스크롤할 때 버벅거립니다."
    validations:
      required: true
      
  - type: dropdown
    id: performance-area
    attributes:
      label: 📍 성능 이슈 영역
      description: 성능 문제가 발생하는 영역을 선택해주세요.
      options:
        - 🌐 페이지 로딩 속도
        - 🔄 API 응답 시간
        - 🖱️ 사용자 인터랙션 반응성
        - 📊 차트/그래프 렌더링
        - 🔍 검색 및 필터링
        - 📱 모바일 성능
        - 💾 메모리 사용량
        - 🔋 배터리 소모 (모바일)
        - 🌐 네트워크 사용량
        - 기타
    validations:
      required: true
      
  - type: textarea
    id: performance-measurements
    attributes:
      label: 📏 성능 측정값
      description: 구체적인 성능 수치를 제공해주세요.
      placeholder: |
        현재 측정값:
        - 페이지 로딩 시간: 5.2초
        - API 응답 시간: 2.1초
        - First Contentful Paint: 3.8초
        - Largest Contentful Paint: 5.2초
        
        기대값:
        - 페이지 로딩 시간: <2초
        - API 응답 시간: <500ms
      render: markdown
      
  - type: textarea
    id: measurement-method
    attributes:
      label: 🔧 측정 방법
      description: 성능을 어떻게 측정했는지 설명해주세요.
      placeholder: |
        - 브라우저 개발자 도구 Network 탭 사용
        - Lighthouse Performance 스코어: 45/100
        - 실제 사용자 환경에서 스톱워치로 측정
        - Chrome DevTools Performance 프로파일링
      value: |
        측정 도구: 
        측정 횟수: 
        측정 조건: 
        측정 시점: 
        
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 재현 단계
      description: 성능 문제를 재현하기 위한 단계를 작성해주세요.
      placeholder: |
        1. 메인 페이지에서 로그인
        2. '챌린지' 메뉴 클릭
        3. 목록이 로드될 때까지 시간 측정
        4. 페이지를 아래로 스크롤
        5. 렉(lag) 현상 관찰
    validations:
      required: true
      
  - type: textarea
    id: environment-details
    attributes:
      label: 🌐 환경 세부사항
      description: 성능 테스트를 진행한 환경의 세부사항을 제공해주세요.
      placeholder: |
        시스템 사양:
        - CPU: Intel i7-10700K / Apple M1
        - RAM: 16GB
        - 저장소: SSD 500GB
        
        네트워크:
        - 연결: WiFi / LTE / 5G
        - 속도: 100Mbps / 50Mbps
        - 지연시간: 20ms
        
        브라우저:
        - 브라우저: Chrome 120.0.6099.109
        - 확장 프로그램: AdBlock, LastPass
        - 시크릿 모드 테스트: Yes/No
      value: |
        시스템 사양:
        - CPU: 
        - RAM: 
        - 저장소: 
        
        네트워크:
        - 연결 타입: 
        - 속도: 
        - 지연시간: 
        
        브라우저:
        - 브라우저: 
        - 버전: 
        - 확장 프로그램: 
        - 시크릿 모드 테스트: 
        
  - type: textarea
    id: data-scale
    attributes:
      label: 📊 데이터 규모
      description: 성능 테스트 시의 데이터 규모를 설명해주세요.
      placeholder: |
        - 챌린지 수: 50개
        - 포트폴리오 포지션: 10개
        - 가격 데이터 범위: 1년간
        - 동시 접속자: 예상 100명
        
  - type: textarea
    id: profiling-data
    attributes:
      label: 🔍 프로파일링 데이터
      description: 브라우저 개발자 도구나 기타 도구로 수집한 프로파일링 데이터가 있다면 첨부해주세요.
      placeholder: |
        Performance 탭 스크린샷, Lighthouse 리포트, 
        Network 탭 HAR 파일 등을 첨부해주세요.
        
  - type: textarea
    id: impact-assessment
    attributes:
      label: 📈 영향도 평가
      description: 이 성능 문제가 사용자 경험에 미치는 영향을 평가해주세요.
      placeholder: |
        - 사용자 이탈 가능성: High/Medium/Low
        - 기능 사용성 저해: High/Medium/Low  
        - 교육 효과 감소: High/Medium/Low
        - 모바일 사용 불편: High/Medium/Low
        
        구체적 영향:
        - 챌린지 참여율 감소 예상
        - 실시간 거래 경험 저해
        - 모바일 사용자 이탈 가능
        
  - type: textarea
    id: potential-causes
    attributes:
      label: 🔍 추정 원인
      description: 성능 문제의 원인으로 추정되는 부분이 있다면 제안해주세요.
      placeholder: |
        - N+1 쿼리 문제 (챌린지-인스트루먼트 조회)
        - 프론트엔드 번들 크기 과다
        - 이미지 최적화 부재
        - 데이터베이스 인덱스 부재
        - Redis 캐시 미적용
        - 불필요한 API 호출
        
  - type: textarea
    id: suggested-solutions
    attributes:
      label: 💡 제안 해결책
      description: 성능 개선을 위한 해결책이 있다면 제안해주세요.
      placeholder: |
        단기 해결책:
        - API 응답 압축 활성화
        - 이미지 lazy loading 적용
        - 페이지네이션 도입
        
        장기 해결책:
        - 데이터베이스 쿼리 최적화
        - CDN 도입
        - 서버 사이드 캐싱 강화
        
  - type: dropdown
    id: urgency
    attributes:
      label: 🚨 긴급도
      description: 이 성능 이슈의 긴급도를 평가해주세요.
      options:
        - 🔴 Critical (서비스 사용 불가 수준)
        - 🟠 High (사용자 경험 크게 저해)
        - 🟡 Medium (불편하지만 사용 가능)
        - 🟢 Low (개선되면 좋은 수준)
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: 📝 추가 정보
      description: 성능 이슈와 관련된 추가 정보나 컨텍스트를 제공해주세요.
      placeholder: |
        - 특정 시간대에만 발생하는지
        - 특정 데이터나 조건에서만 발생하는지
        - 다른 사용자들도 비슷한 문제를 겪는지
        - 성능 저하가 언제부터 시작되었는지
        
  - type: checkboxes
    id: performance-checklist
    attributes:
      label: ✅ 성능 이슈 체크리스트
      description: 성능 이슈를 제출하기 전에 다음 사항을 확인해주세요.
      options:
        - label: 여러 번 재현하여 일관된 성능 문제를 확인했습니다.
          required: true
        - label: 브라우저 캐시를 클리어하고 테스트했습니다.
          required: true
        - label: 시크릿/프라이빗 모드에서도 동일한 문제가 발생하는지 확인했습니다.
          required: true
        - label: 다른 브라우저에서도 테스트해봤습니다.
          required: true
        - label: 네트워크 상태를 고려하여 측정했습니다.
          required: true
        - label: 구체적인 성능 수치를 제공했습니다.
          required: true