name: ❓ 질문
description: StockQuest 사용법이나 개발에 대한 질문
title: "❓ [Question]: "
labels: ["question", "help-wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ❓ 질문해주셔서 감사합니다!
        
        명확한 답변을 드리기 위해 구체적인 정보를 제공해주세요.
        일반적인 토론은 [Discussions](https://github.com/seongmin1117/stock-quest/discussions)를 이용해주세요.
        
  - type: dropdown
    id: question-type
    attributes:
      label: 🏷️ 질문 유형
      description: 질문의 유형을 선택해주세요.
      options:
        - 💻 개발/코드 관련
        - 🎯 기능 사용법
        - 🏗️ 아키텍처/설계
        - 🚀 배포/운영
        - 📚 문서/가이드
        - 🔧 설정/환경
        - 🐛 트러블슈팅
        - 기타
    validations:
      required: true
      
  - type: textarea
    id: question-details
    attributes:
      label: ❓ 질문 내용
      description: 구체적인 질문을 작성해주세요.
      placeholder: |
        예시:
        - 새로운 도메인 엔티티를 추가할 때 어떤 순서로 작업해야 하나요?
        - 포트폴리오 계산 로직은 어디에 구현되어 있나요?
        - 개발 환경 설정 중 MySQL 연결 오류가 발생합니다.
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: 🔍 배경/컨텍스트
      description: 질문과 관련된 배경 정보나 상황을 설명해주세요.
      placeholder: |
        - 무엇을 하려고 하는지
        - 어떤 문제를 해결하려고 하는지
        - 지금까지 시도해본 것들
        - 참고한 문서나 코드
        
  - type: textarea
    id: what-tried
    attributes:
      label: 🔄 시도한 방법
      description: 이미 시도해본 방법이나 확인한 내용이 있다면 작성해주세요.
      placeholder: |
        - 문서 확인: README.md, 위키 페이지
        - 코드 검색: 관련 파일이나 클래스명으로 검색
        - 구글링: 관련 키워드로 검색
        - 기존 이슈: GitHub 이슈에서 유사 질문 검색
        
  - type: textarea
    id: expected-answer
    attributes:
      label: 🎯 원하는 답변
      description: 어떤 형태의 답변을 원하시는지 알려주세요.
      placeholder: |
        - 구체적인 코드 예시
        - 단계별 가이드
        - 개념 설명
        - 관련 문서 링크
        - 모범 사례
        
  - type: textarea
    id: environment
    attributes:
      label: 🌐 환경 정보 (필요시)
      description: 환경과 관련된 질문이라면 환경 정보를 제공해주세요.
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - Java: 21.0.1
        - Node.js: 18.17.0
        - IDE: IntelliJ IDEA / VS Code
        - Docker: 24.0.5
        
  - type: checkboxes
    id: question-checklist
    attributes:
      label: ✅ 질문 전 체크리스트
      description: 질문하기 전에 다음 사항을 확인해주세요.
      options:
        - label: README.md와 관련 문서를 확인했습니다.
          required: true
        - label: 기존 이슈와 Discussions에서 유사한 질문을 검색했습니다.
          required: true
        - label: 구체적이고 명확한 질문을 작성했습니다.
          required: true
        - label: 충분한 배경 정보를 제공했습니다.
          required: true