# ===================================================================
# 개발 환경 설정 (application-dev.yml)
# Docker Compose MySQL/Redis 연결 최적화
# ===================================================================

spring:
  # 데이터베이스 설정 - Docker MySQL 최적화
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stockquest?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&useLocalSessionState=true&rewriteBatchedStatements=true
    username: root
    password: rootpassword
    
    # HikariCP 개발 환경 최적화 (2025-09-21 성능 분석 기반)
    hikari:
      pool-name: "StockQuest-Dev-HikariCP"
      minimum-idle: 5              # 2→5: 개발 생산성 향상
      maximum-pool-size: 15        # 10→15: 동시 개발자 지원 확대
      connection-timeout: 15000    # 20s→15s: 더 빠른 실패 감지
      idle-timeout: 600000         # 5min→10min: 개발 세션 안정성
      max-lifetime: 1800000        # 20min→30min: 장기 개발 세션 지원
      leak-detection-threshold: 45000  # 60s→45s: 더 빠른 누수 감지
      keepalive-time: 300000       # 5min: 연결 드롭 방지 NEW
      connection-test-query: "SELECT 1"
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"

      # 개발 환경 모니터링 활성화
      register-mbeans: true        # NEW: JMX 모니터링 활성화
      validation-timeout: 3000     # NEW: 빠른 연결 검증
      
      # MySQL Driver 최적화 설정
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  # JPA/Hibernate 개발 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        # Hibernate Second-level Cache 활성화 (EhCache) - Hibernate 6.x 설정
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        # JCache Provider 설정
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: classpath:ehcache.xml
        jdbc:
          batch_size: 25
          fetch_size: 50
          lob:
            non_contextual_creation: true

  # Redis 개발 환경 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000ms

  # 캐시 개발 설정
  cache:
    type: redis
    redis:
      time-to-live: 1800s  # 30분 (개발용 짧게 설정)

# 로깅 설정 - 개발 환경
logging:
  level:
    root: INFO
    com.stockquest: DEBUG
    com.stockquest.adapter.out.security.JwtTokenProvider: WARN
    org.springframework.security: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.data.jpa: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){faint} %clr(%-5level){spring} [%X{traceId:-}] %clr(%logger{36}){cyan} - %msg%n"
    
# 개발용 성능 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 개발 환경에서는 모든 endpoint 노출
  endpoint:
    health:
      show-details: always
    env:
      show-values: always  # 개발 환경에서는 환경변수 값도 노출

# 애플리케이션 개발 설정
app:
  environment: development
  mail:
    enabled: false

# 개발용 비동기 처리 설정
async:
  core-pool-size: 5
  max-pool-size: 20
  queue-capacity: 100

# 개발용 캐시 통계 활성화
cache:
  statistics:
    enabled: true

# 개발용 외부 API 설정
yahoo-finance:
  timeout: 10000  # 개발 환경에서는 더 긴 타임아웃

# 개발용 시뮬레이션 설정
stockquest:
  # 거래 시뮬레이션 설정 (개발 환경)
  trading:
    # 시뮬레이션 모드 활성화 (외부 API 없이 완전 동작)
    simulation-mode: true

    # 슬리피지 설정
    slippage:
      min: 0.5
      max: 2.0

    # 변동성 설정
    volatility:
      price-variation: 5.0
      time-based-variation: true

    # 티커별 기본 가격 (더미 데이터 보완)
    default-prices:
      # 미국 주식 (USD)
      AAPL: 180.00
      MSFT: 420.00
      GOOGL: 140.00
      GOOG: 140.00
      AMZN: 150.00
      TSLA: 250.00
      NVDA: 450.00
      META: 350.00
      NFLX: 400.00
      AMD: 120.00
      INTC: 35.00

      # 밈스톡 (2021년 기준)
      GME: 20.00
      AMC: 10.00
      BB: 8.00
      NOK: 5.00
      KOSS: 15.00

      # 방어적 자산
      JNJ: 165.00
      PG: 150.00
      KO: 62.00

      # 한국 주식 (KRW)
      "005930": 70000.00  # 삼성전자
      "000660": 120000.00 # SK하이닉스
      "035720": 95000.00  # 카카오

      # 기본 fallback
      DEFAULT: 100.00

  simulation:
    batch-size: 10  # 개발용 작은 배치 크기
    thread-pool-size: 2
    max-concurrent-sessions: 100

