spring:
  application:
    name: stockquest-api
  profiles:
    active: dev
    include: security
  
  # 데이터베이스 설정 (환경별 파일에서 오버라이드)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none  # DB 스키마 작업 비활성화
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      
  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# JWT 설정
jwt:
  secret: stockquest-jwt-secret-key-for-development-only
  expiration: 86400000  # 24시간 (밀리초)

# API 문서 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env
        exclude: shutdown
      base-path: /actuator
      cors:
        allowed-origins: ${app.cors.allowed-origins:http://localhost:3000}
        allowed-methods: GET,POST
        
  endpoint:
    health:
      show-details: always
      show-components: always
    env:
      show-values: when-authorized

  # 메트릭 설정
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
    tags:
      application: ${spring.application.name}
      environment: ${app.environment:development}

  # Health Check 설정
  health:
    redis:
      enabled: true
    db:
      enabled: true
    defaults:
      enabled: true

# 애플리케이션 정보
info:
  app:
    name: StockQuest API
    description: Stock Trading Simulation Platform
    version: '@project.version@'
    encoding: UTF-8
    java:
      version: '@java.version@'

# 앱 설정
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}
  environment: ${ENVIRONMENT:development}
    
# 외부 API 설정
yahoo-finance:
  base-url: https://query1.finance.yahoo.com
  timeout: 5000
  rate-limit: 2000 # 2초당 1회

# 애플리케이션 설정
stockquest:
  challenge:
    max-speed-factor: 100  # 최대 100배속
    default-seed-balance: 1000000  # 기본 시드머니 100만원
  simulation:
    tick-interval: 10000  # 시뮬레이션 틱 간격 (밀리초)
    max-sessions-per-batch: 50  # 배치당 최대 세션 처리 수
    enable-auto-completion: true  # 자동 세션 완료 활성화
    progress-log-interval: 10  # 진행률 로깅 간격 (%)
  trading:
    slippage:
      min: 0.5  # 최소 슬리피지 (%)
      max: 2.0  # 최대 슬리피지 (%)
    commission-rate: 0.0025  # 거래 수수료율 (0.25%)