name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: stockquest_test
          MYSQL_ROOT_PASSWORD: test123
          MYSQL_USER: stockquest
          MYSQL_PASSWORD: test123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
      
    - name: Run tests
      run: |
        cd backend
        ./gradlew test --info
      env:
        SPRING_PROFILES_ACTIVE: test
        DB_HOST: localhost
        DB_PORT: 3306
        DB_NAME: stockquest_test
        DB_USERNAME: stockquest
        DB_PASSWORD: test123
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        JWT_SECRET: test_secret_key_for_testing_only_32_characters_long
      
    - name: Generate test report
      if: always()
      run: |
        cd backend
        ./gradlew jacocoTestReport
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: backend/build/test-results/
    
    - name: Upload coverage reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: backend/build/reports/jacoco/
      
    - name: Build application
      run: |
        cd backend
        ./gradlew build -x test
      
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: application-jar
        path: backend/build/libs/*.jar

  code-quality:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Run SpotBugs
      run: |
        cd backend
        ./gradlew spotbugsMain || true
      continue-on-error: true
    
    - name: Run Checkstyle
      run: |
        cd backend
        ./gradlew checkstyleMain || true
      continue-on-error: true