name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Setup npm cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Generate API client
      run: |
        cd frontend
        npm run generate-api

    - name: Run linter
      run: |
        cd frontend
        npm run lint -- --max-warnings 200
      continue-on-error: true
    
    - name: Run type check
      run: |
        cd frontend
        npm run type-check || echo "Type check failed but continuing..."
      continue-on-error: true
    
    - name: Run tests
      run: |
        cd frontend
        npm run test:coverage || npm run test || echo "Tests failed but continuing..."
      env:
        CI: true
      continue-on-error: true
    
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: frontend/coverage/
      continue-on-error: true
      if: always()
    
    - name: Build application
      run: |
        cd frontend
        npm run build
      env:
        NEXT_PUBLIC_API_BASE_URL: ${{ secrets.API_BASE_URL || 'http://localhost:8080' }}
        NEXT_PUBLIC_MOCK_API: false
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/.next/

  e2e-tests:
    runs-on: ubuntu-latest
    needs: test-and-build
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Generate API client
      run: |
        cd frontend
        npm run generate-api

    - name: Install Playwright browsers
      run: |
        cd frontend
        npx playwright install --with-deps
    
    - name: Run E2E tests
      run: |
        cd frontend
        npm run test:e2e || echo "E2E tests failed but continuing..."
      env:
        CI: true
        NEXT_PUBLIC_MOCK_API: true
      continue-on-error: true
    
    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30

  lighthouse:
    runs-on: ubuntu-latest
    needs: test-and-build
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Generate API client
      run: |
        cd frontend
        npm run generate-api

    - name: Build application
      run: |
        cd frontend
        npm run build
      env:
        NEXT_PUBLIC_MOCK_API: true
    
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli
        cd frontend
        lhci autorun --config=.lighthouserc.js || true
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      continue-on-error: true